# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'y:\passeratorgui.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(394, 397)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.txtNumPassword = QtWidgets.QLabel(self.centralwidget)
        self.txtNumPassword.setObjectName("txtNumPassword")
        self.horizontalLayout_3.addWidget(self.txtNumPassword)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.spNumber = QtWidgets.QSpinBox(self.centralwidget)
        self.spNumber.setMinimum(1)
        self.spNumber.setObjectName("spNumber")
        self.horizontalLayout_3.addWidget(self.spNumber)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.txtSizePassword = QtWidgets.QLabel(self.centralwidget)
        self.txtSizePassword.setObjectName("txtSizePassword")
        self.horizontalLayout_4.addWidget(self.txtSizePassword)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.spSize = QtWidgets.QSpinBox(self.centralwidget)
        self.spSize.setMinimum(1)
        self.spSize.setObjectName("spSize")
        self.horizontalLayout_4.addWidget(self.spSize)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.txtSpecial = QtWidgets.QLabel(self.centralwidget)
        self.txtSpecial.setObjectName("txtSpecial")
        self.horizontalLayout_5.addWidget(self.txtSpecial)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.chkWithSpecial = QtWidgets.QCheckBox(self.centralwidget)
        self.chkWithSpecial.setText("")
        self.chkWithSpecial.setCheckable(True)
        self.chkWithSpecial.setObjectName("chkWithSpecial")
        self.horizontalLayout_5.addWidget(self.chkWithSpecial)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.txtWithNumber = QtWidgets.QLabel(self.centralwidget)
        self.txtWithNumber.setObjectName("txtWithNumber")
        self.horizontalLayout_6.addWidget(self.txtWithNumber)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.chkWithNumber = QtWidgets.QCheckBox(self.centralwidget)
        self.chkWithNumber.setText("")
        self.chkWithNumber.setObjectName("chkWithNumber")
        self.horizontalLayout_6.addWidget(self.chkWithNumber)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.txtSimilar = QtWidgets.QLabel(self.centralwidget)
        self.txtSimilar.setObjectName("txtSimilar")
        self.horizontalLayout_7.addWidget(self.txtSimilar)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.chkWithSimilar = QtWidgets.QCheckBox(self.centralwidget)
        self.chkWithSimilar.setText("")
        self.chkWithSimilar.setObjectName("chkWithSimilar")
        self.horizontalLayout_7.addWidget(self.chkWithSimilar)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.txtAccent = QtWidgets.QLabel(self.centralwidget)
        self.txtAccent.setObjectName("txtAccent")
        self.horizontalLayout_8.addWidget(self.txtAccent)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.chkWithAccent = QtWidgets.QCheckBox(self.centralwidget)
        self.chkWithAccent.setText("")
        self.chkWithAccent.setObjectName("chkWithAccent")
        self.horizontalLayout_8.addWidget(self.chkWithAccent)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.txtUppercase = QtWidgets.QLabel(self.centralwidget)
        self.txtUppercase.setObjectName("txtUppercase")
        self.horizontalLayout_9.addWidget(self.txtUppercase)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem7)
        self.chkWithUppercase = QtWidgets.QCheckBox(self.centralwidget)
        self.chkWithUppercase.setText("")
        self.chkWithUppercase.setObjectName("chkWithUppercase")
        self.horizontalLayout_9.addWidget(self.chkWithUppercase)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.txtLowercase = QtWidgets.QLabel(self.centralwidget)
        self.txtLowercase.setObjectName("txtLowercase")
        self.horizontalLayout_10.addWidget(self.txtLowercase)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem8)
        self.chkWithLowercase = QtWidgets.QCheckBox(self.centralwidget)
        self.chkWithLowercase.setText("")
        self.chkWithLowercase.setObjectName("chkWithLowercase")
        self.horizontalLayout_10.addWidget(self.chkWithLowercase)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem9)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.btGenerate = QtWidgets.QPushButton(self.centralwidget)
        self.btGenerate.setObjectName("btGenerate")
        self.verticalLayout.addWidget(self.btGenerate)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.teResult = QtWidgets.QTextEdit(self.centralwidget)
        self.teResult.setReadOnly(True)
        self.teResult.setObjectName("teResult")
        self.horizontalLayout_2.addWidget(self.teResult)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem10)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.btCopy = QtWidgets.QPushButton(self.centralwidget)
        self.btCopy.setObjectName("btCopy")
        self.verticalLayout_5.addWidget(self.btCopy)
        self.btClose = QtWidgets.QPushButton(self.centralwidget)
        self.btClose.setObjectName("btClose")
        self.verticalLayout_5.addWidget(self.btClose)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.btClose.clicked.connect(MainWindow.close)
        self.btCopy.clicked.connect(self.teResult.copy)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.spNumber, self.spSize)
        MainWindow.setTabOrder(self.spSize, self.chkWithSpecial)
        MainWindow.setTabOrder(self.chkWithSpecial, self.chkWithNumber)
        MainWindow.setTabOrder(self.chkWithNumber, self.chkWithSimilar)
        MainWindow.setTabOrder(self.chkWithSimilar, self.chkWithAccent)
        MainWindow.setTabOrder(self.chkWithAccent, self.chkWithUppercase)
        MainWindow.setTabOrder(self.chkWithUppercase, self.chkWithLowercase)
        MainWindow.setTabOrder(self.chkWithLowercase, self.btGenerate)
        MainWindow.setTabOrder(self.btGenerate, self.teResult)
        MainWindow.setTabOrder(self.teResult, self.btCopy)
        MainWindow.setTabOrder(self.btCopy, self.btClose)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.txtNumPassword.setText(_translate("MainWindow", "Number"))
        self.txtSizePassword.setText(_translate("MainWindow", "Size"))
        self.txtSpecial.setText(_translate("MainWindow", "special"))
        self.txtWithNumber.setText(_translate("MainWindow", "Number"))
        self.txtSimilar.setText(_translate("MainWindow", "Similar"))
        self.txtAccent.setText(_translate("MainWindow", "Accent"))
        self.txtUppercase.setText(_translate("MainWindow", "Uppercase"))
        self.txtLowercase.setText(_translate("MainWindow", "Lowercase"))
        self.btGenerate.setText(_translate("MainWindow", "Generate"))
        self.btCopy.setText(_translate("MainWindow", "Copy"))
        self.btClose.setText(_translate("MainWindow", "Close"))

